feat: sprint 9 homework
temanaganov/java-filmorate pull request #1
Opened 2022-10-26 22:08 UTC by temanaganov

2022-10-27 18:13 UTC, kalitva requested changes

2022-10-27 18:13 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/film/FilmController.java
> +import org.springframework.web.bind.annotation.*;
Не используй wildcard imports

https://google.github.io/styleguide/javaguide.html#s3.3.1-wildcard-imports

2022-10-27 18:13 UTC, kalitva commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	@Test
Нужно будет добавить тесты для контроллеров

2022-10-27 20:51 UTC, temanaganov commented on HELP.md
> +# Getting Started
Удалил

2022-10-27 20:51 UTC, temanaganov commented on pom.xml
> +	<modelVersion>4.0.0</modelVersion>
Не специально, видимо он сгенерировался с табами, поправил

2022-10-27 20:51 UTC, temanaganov commented on pom.xml
> +			<version>1.18.24</version>
Убрал

2022-10-27 20:51 UTC, temanaganov commented on src/main/java/ru/yandex/practicum/filmorate/film/FilmController.java
> +@Slf4j
Теперь использую

2022-10-27 20:51 UTC, temanaganov commented on src/main/java/ru/yandex/practicum/filmorate/film/FilmController.java
> +    private final FilmService filmService = new InMemoryFilmService();
Сделал DI

2022-10-27 20:52 UTC, temanaganov commented on src/main/java/ru/yandex/practicum/filmorate/film/FilmController.java
> +    public Film getFilm(@PathVariable("id") int id) {
Поправил

2022-10-27 20:52 UTC, temanaganov commented on src/main/java/ru/yandex/practicum/filmorate/film/FilmController.java
> +            throw new ResponseStatusException(HttpStatus.NOT_FOUND);
Сделал

2022-10-27 20:52 UTC, temanaganov commented on src/main/java/ru/yandex/practicum/filmorate/film/FilmService.java
> +    Film updateFilm(int id, Film film);
Да, правда не нужен оказался

2022-10-27 20:52 UTC, temanaganov commented on src/main/java/ru/yandex/practicum/filmorate/film/InMemoryFilmService.java
> +        Film newFilm = new Film(getNextId(), film.getName(), film.getDescription(), film.getReleaseDate(), film.getDuration());
Добавил, спасибо

2022-10-27 20:52 UTC, temanaganov commented on src/main/java/ru/yandex/practicum/filmorate/film/InMemoryFilmService.java
> +    public Film updateFilm(int id, Film film) {
Добавил легирование

2022-10-27 20:53 UTC, temanaganov commented on src/main/java/ru/yandex/practicum/filmorate/film/FilmController.java
> +import org.springframework.web.bind.annotation.*;
Их IDEA автоматически делает, не увидел, поправил

2022-10-27 20:55 UTC, temanaganov commented on src/main/java/ru/yandex/practicum/filmorate/film/Film.java
> +    int duration;
Пока решил оставить int, т.к. не нашел пока, как по нормальному сделать десериализацию числа в минутах в Duration, пробовал аннотации `@JsonSerializer` и `@JsonDeserializer`, но не особо помогло

2022-10-27 20:56 UTC, temanaganov commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	@Test
Оставил пока до будущих спринтов, т.к. не проходили, или же сделаю в оставшееся время до следующего спринта, если будет свободное время

2022-10-28 17:11 UTC, kalitva approved these changes

2022-10-28 18:21 UTC, temanaganov commented on src/main/java/ru/yandex/practicum/filmorate/user/User.java
> +    @DateTimeFormat(pattern = "YYYY-mm-dd")
Я так понял, это валидация даты по паттерну, если не в таком формате прислать, отстреливает 400

2022-10-31 22:03 UTC, merged